# Generated by Django 3.1.6 on 2021-05-15 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('descriptions', models.CharField(max_length=399)),
                ('publish_date', models.DateField(verbose_name=datetime.date)),
            ],
        ),
    ]
