# Generated by Django 3.1.6 on 2021-05-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210516_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('phone', models.IntegerField(default=0, max_length=12)),
                ('desc', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
